// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwdbyoswynbwtxdalffy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3ZGJ5b3N3eW5id3R4ZGFsZmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTcwNDAsImV4cCI6MjA3MDY3MzA0MH0.irSvwFKGaLQtpimMpIsg0o5t4ii78cK37_xEIXvaAfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});